interface CBarnLight {
    "Enabled": boolean;
    "ColorMode": number;
    "Color": Color;
    "ColorTemperature": number;
    "Brightness": number;
    "BrightnessScale": number;
    "DirectLight": number;
    "BakedShadowIndex": number;
    "LuminaireShape": number;
    "LuminaireSize": number;
    "LuminaireAnisotropy": number;
    "LightStyleString": string;
    "LightStyleStartTime": number;
    readonly "QueuedLightStyleStrings": Object;
    readonly "LightStyleEvents": Object;
    readonly "StyleEvent": Object;
    "Shape": number;
    "SoftX": number;
    "SoftY": number;
    "Skirt": number;
    "SkirtNear": number;
    "SizeParams": Vector;
    "Range": number;
    "Shear": Vector;
    "BakeSpecularToCubemaps": number;
    "BakeSpecularToCubemapsSize": Vector;
    "CastShadows": number;
    "ShadowMapSize": number;
    "ShadowPriority": number;
    "ContactShadow": boolean;
    "BounceLight": number;
    "BounceScale": number;
    "MinRoughness": number;
    "AlternateColor": Vector;
    "AlternateColorBrightness": number;
    "Fog": number;
    "FogStrength": number;
    "FogShadows": number;
    "FogScale": number;
    "FogMixedShadows": boolean;
    "FadeSizeStart": number;
    "FadeSizeEnd": number;
    "ShadowFadeSizeStart": number;
    "ShadowFadeSizeEnd": number;
    "PrecomputedFieldsValid": boolean;
    "PrecomputedBoundsMins": Vector;
    "PrecomputedBoundsMaxs": Vector;
    "PrecomputedOBBOrigin": Vector;
    "PrecomputedOBBAngles": QAngle;
    "PrecomputedOBBExtent": Vector;
    "PrecomputedSubFrusta": number;
    "PrecomputedOBBOrigin0": Vector;
    "PrecomputedOBBAngles0": QAngle;
    "PrecomputedOBBExtent0": Vector;
    "PrecomputedOBBOrigin1": Vector;
    "PrecomputedOBBAngles1": QAngle;
    "PrecomputedOBBExtent1": Vector;
    "PrecomputedOBBOrigin2": Vector;
    "PrecomputedOBBAngles2": QAngle;
    "PrecomputedOBBExtent2": Vector;
    "PrecomputedOBBOrigin3": Vector;
    "PrecomputedOBBAngles3": QAngle;
    "PrecomputedOBBExtent3": Vector;
    "PrecomputedOBBOrigin4": Vector;
    "PrecomputedOBBAngles4": QAngle;
    "PrecomputedOBBExtent4": Vector;
    "PrecomputedOBBOrigin5": Vector;
    "PrecomputedOBBAngles5": QAngle;
    "PrecomputedOBBExtent5": Vector;
    "PvsModifyEntity": boolean;
    readonly "VisClusters": Object;
    readonly "Parent": CBaseModelEntity;
    ToPtr: () => string;
    IsValid: () => boolean;
}

declare function CBarnLight(ptr_or_class: string|AnySDKClass): CBarnLight;