interface CBaseModelEntity {
    readonly "CRenderComponent": CRenderComponent;
    readonly "CHitboxComponent": CHitboxComponent;
    "DestructiblePartInitialStateDestructed0": number;
    "DestructiblePartInitialStateDestructed1": number;
    "DestructiblePartInitialStateDestructed2": number;
    "DestructiblePartInitialStateDestructed3": number;
    "DestructiblePartInitialStateDestructed4": number;
    "LastHitDestructiblePartIndex": number;
    "LastHitGroup": number;
    "DissolveStartTime": number;
    readonly "OnIgnite": CEntityIOOutput;
    "RenderMode": number;
    "RenderFX": number;
    "AllowFadeInView": boolean;
    "Render": Color;
    readonly "RenderAttributes": Object;
    "RenderToCubemaps": boolean;
    "NoInterpolate": boolean;
    readonly "Collision": CCollisionProperty;
    readonly "Glow": CGlowProperty;
    "GlowBackfaceMult": number;
    "FadeMinDist": number;
    "FadeMaxDist": number;
    "FadeScale": number;
    "ShadowStrength": number;
    "ObjectCulling": number;
    "AddDecal": number;
    "DecalPosition": Vector;
    "DecalForwardAxis": Vector;
    "DecalHealBloodRate": number;
    "DecalHealHeightRate": number;
    readonly "ViewOffset": CNetworkViewOffsetVector;
    readonly "Parent": CBaseEntity;
    SetBodygroup: (str: string,val: any) => null|undefined;
    SetModel: (model: string) => null|undefined;
    SetSolidType: (solidType: number) => null|undefined;
    ToPtr: () => string;
    IsValid: () => boolean;
}

declare function CBaseModelEntity(ptr_or_class: string|AnySDKClass): CBaseModelEntity;