interface CCSBot {
    "EyePosition": Vector;
    "Name": string;
    "CombatRange": number;
    "IsRogue": boolean;
    readonly "RogueTimer": CountdownTimer;
    "DiedLastRound": boolean;
    "SafeTime": number;
    "WasSafe": boolean;
    "BlindFire": boolean;
    readonly "SurpriseTimer": CountdownTimer;
    "AllowActive": boolean;
    "IsFollowing": boolean;
    readonly "Leader": CCSPlayerPawn;
    "FollowTimestamp": number;
    "AllowAutoFollowTime": number;
    readonly "HurryTimer": CountdownTimer;
    readonly "AlertTimer": CountdownTimer;
    readonly "SneakTimer": CountdownTimer;
    readonly "PanicTimer": CountdownTimer;
    "StateTimestamp": number;
    "IsAttacking": boolean;
    "IsOpeningDoor": boolean;
    readonly "TaskEntity": CBaseEntity;
    "GoalPosition": Vector;
    readonly "GoalEntity": CBaseEntity;
    readonly "Avoid": CBaseEntity;
    "AvoidTimestamp": number;
    "IsStopping": boolean;
    "HasVisitedEnemySpawn": boolean;
    readonly "StillTimer": IntervalTimer;
    "EyeAnglesUnderPathFinderControl": boolean;
    "PathIndex": number;
    "AreaEnteredTimestamp": number;
    readonly "RepathTimer": CountdownTimer;
    readonly "AvoidFriendTimer": CountdownTimer;
    "IsFriendInTheWay": boolean;
    readonly "PoliteTimer": CountdownTimer;
    "IsWaitingBehindFriend": boolean;
    "PathLadderEnd": number;
    readonly "MustRunTimer": CountdownTimer;
    readonly "WaitTimer": CountdownTimer;
    readonly "UpdateTravelDistanceTimer": CountdownTimer;
    "PlayerTravelDistance": Object;
    "TravelDistancePhase": number;
    "HostageEscortCount": number;
    "HostageEscortCountTimestamp": number;
    "DesiredTeam": number;
    "HasJoined": boolean;
    "IsWaitingForHostage": boolean;
    readonly "InhibitWaitingForHostageTimer": CountdownTimer;
    readonly "WaitForHostageTimer": CountdownTimer;
    "NoisePosition": Vector;
    "NoiseTravelDistance": number;
    "NoiseTimestamp": number;
    readonly "NoiseSource": CCSPlayerPawn;
    readonly "NoiseBendTimer": CountdownTimer;
    "BentNoisePosition": Vector;
    "BendNoisePositionValid": boolean;
    "LookAroundStateTimestamp": number;
    "LookAheadAngle": number;
    "ForwardAngle": number;
    "InhibitLookAroundTimestamp": number;
    "LookAtSpot": Vector;
    "LookAtSpotDuration": number;
    "LookAtSpotTimestamp": number;
    "LookAtSpotAngleTolerance": number;
    "LookAtSpotClearIfClose": boolean;
    "LookAtSpotAttack": boolean;
    "LookAtDesc": string;
    "PeripheralTimestamp": number;
    "ApproachPointCount": number;
    "ApproachPointViewPosition": Vector;
    readonly "ViewSteadyTimer": IntervalTimer;
    readonly "TossGrenadeTimer": CountdownTimer;
    readonly "IsAvoidingGrenade": CountdownTimer;
    "SpotCheckTimestamp": number;
    "CheckedHidingSpotCount": number;
    "LookPitch": number;
    "LookPitchVel": number;
    "LookYaw": number;
    "LookYawVel": number;
    "TargetSpot": Vector;
    "TargetSpotVelocity": Vector;
    "TargetSpotPredicted": Vector;
    "AimError": QAngle;
    "AimGoal": QAngle;
    "TargetSpotTime": number;
    "AimFocus": number;
    "AimFocusInterval": number;
    "AimFocusNextUpdate": number;
    readonly "IgnoreEnemiesTimer": CountdownTimer;
    readonly "Enemy": CCSPlayerPawn;
    "IsEnemyVisible": boolean;
    "VisibleEnemyParts": number;
    "LastEnemyPosition": Vector;
    "LastSawEnemyTimestamp": number;
    "FirstSawEnemyTimestamp": number;
    "CurrentEnemyAcquireTimestamp": number;
    "EnemyDeathTimestamp": number;
    "FriendDeathTimestamp": number;
    "IsLastEnemyDead": boolean;
    "NearbyEnemyCount": number;
    readonly "Bomber": CCSPlayerPawn;
    "NearbyFriendCount": number;
    readonly "ClosestVisibleFriend": CCSPlayerPawn;
    readonly "ClosestVisibleHumanFriend": CCSPlayerPawn;
    readonly "AttentionInterval": IntervalTimer;
    readonly "Attacker": CCSPlayerPawn;
    "AttackedTimestamp": number;
    readonly "BurnedByFlamesTimer": IntervalTimer;
    "LastVictimID": number;
    "IsAimingAtEnemy": boolean;
    "IsRapidFiring": boolean;
    readonly "EquipTimer": IntervalTimer;
    readonly "ZoomTimer": CountdownTimer;
    "FireWeaponTimestamp": number;
    readonly "LookForWeaponsOnGroundTimer": CountdownTimer;
    "IsSleeping": boolean;
    "IsEnemySniperVisible": boolean;
    readonly "SawEnemySniperTimer": CountdownTimer;
    "EnemyQueueIndex": number;
    "EnemyQueueCount": number;
    "EnemyQueueAttendIndex": number;
    "IsStuck": boolean;
    "StuckTimestamp": number;
    "StuckSpot": Vector;
    readonly "WiggleTimer": CountdownTimer;
    readonly "StuckJumpTimer": CountdownTimer;
    "NextCleanupCheckTimestamp": number;
    "AvgVel": Object;
    "AvgVelIndex": number;
    "AvgVelCount": number;
    "LastOrigin": Vector;
    "LastRadioRecievedTimestamp": number;
    "LastRadioSentTimestamp": number;
    readonly "RadioSubject": CCSPlayerPawn;
    "RadioPosition": Vector;
    "VoiceEndTimestamp": number;
    "LastValidReactionQueueFrame": number;
    readonly "Parent": CBot;
    ToPtr: () => string;
    IsValid: () => boolean;
}

declare function CCSBot(ptr_or_class: string|AnySDKClass): CCSBot;