interface CCSPlayerPawn {
    readonly "BulletServices": CCSPlayer_BulletServices;
    readonly "HostageServices": CCSPlayer_HostageServices;
    readonly "BuyServices": CCSPlayer_BuyServices;
    readonly "ActionTrackingServices": CCSPlayer_ActionTrackingServices;
    readonly "RadioServices": CCSPlayer_RadioServices;
    readonly "DamageReactServices": CCSPlayer_DamageReactServices;
    "CharacterDefIndex": number;
    "HasFemaleVoice": boolean;
    "StrVOPrefix": string;
    "LastPlaceName": string;
    "InHostageResetZone": boolean;
    "InBuyZone": boolean;
    "WasInBuyZone": boolean;
    "InHostageRescueZone": boolean;
    "InBombZone": boolean;
    "WasInHostageRescueZone": boolean;
    "RetakesOffering": number;
    "RetakesOfferingCard": number;
    "RetakesHasDefuseKit": boolean;
    "RetakesMVPLastRound": boolean;
    "RetakesMVPBoostItem": number;
    "RetakesMVPBoostExtraUtility": number;
    "HealthShotBoostExpirationTime": number;
    "LandingTimeSeconds": number;
    "AimPunchAngle": QAngle;
    "AimPunchAngleVel": QAngle;
    "AimPunchTickBase": number;
    "AimPunchTickFraction": number;
    readonly "AimPunchCache": Object;
    "IsBuyMenuOpen": boolean;
    "LastHeadBoneTransformIsValid": boolean;
    "LastLandTime": number;
    "OnGroundLastTick": boolean;
    "PlayerLocked": number;
    "TimeOfLastInjury": number;
    "NextSprayDecalTime": number;
    "NextSprayDecalTimeExpedited": boolean;
    "RagdollDamageBone": number;
    "RagdollDamageForce": Vector;
    "RagdollDamagePosition": Vector;
    "RagdollDamageWeaponName": string;
    "RagdollDamageHeadshot": boolean;
    "RagdollServerOrigin": Vector;
    readonly "EconGloves": CEconItemView;
    "EconGlovesChanged": number;
    "DeathEyeAngles": QAngle;
    "SkipOneHeadConstraintUpdate": boolean;
    "LeftHanded": boolean;
    "SwitchedHandednessTime": number;
    "ViewmodelOffsetX": number;
    "ViewmodelOffsetY": number;
    "ViewmodelOffsetZ": number;
    "ViewmodelFOV": number;
    "IsWalking": boolean;
    "LastGivenDefuserTime": number;
    "LastGivenBombTime": number;
    "DealtDamageToEnemyMostRecentTimestamp": number;
    "DisplayHistoryBits": number;
    "LastAttackedTeammate": number;
    "AllowAutoFollowTime": number;
    "ResetArmorNextSpawn": boolean;
    "LastKillerIndex": number;
    readonly "EntitySpottedState": EntitySpottedState_t;
    "SpotRules": number;
    "IsScoped": boolean;
    "ResumeZoom": boolean;
    "IsDefusing": boolean;
    "IsGrabbingHostage": boolean;
    "BlockingUseActionInProgress": number;
    "EmitSoundTime": number;
    "InNoDefuseArea": boolean;
    "BombSiteIndex": number;
    "WhichBombZone": number;
    "InBombZoneTrigger": boolean;
    "WasInBombZoneTrigger": boolean;
    "ShotsFired": number;
    "FlinchStack": number;
    "VelocityModifier": number;
    "HitHeading": number;
    "HitBodyPart": number;
    "TotalBulletForce": Vector;
    "WaitForNoAttack": boolean;
    "IgnoreLadderJumpTime": number;
    "KilledByHeadshot": boolean;
    "LastHitBox": number;
    "LastHealth": number;
    readonly "Bot": CCSBot;
    "BotAllowActive": boolean;
    "ThirdPersonHeading": QAngle;
    "SlopeDropOffset": number;
    "SlopeDropHeight": number;
    "HeadConstraintOffset": Vector;
    "LastPickupPriority": number;
    "LastPickupPriorityTime": number;
    "ArmorValue": number;
    "CurrentEquipmentValue": number;
    "RoundStartEquipmentValue": number;
    "FreezetimeEndEquipmentValue": number;
    "LastWeaponFireUsercmd": number;
    "IsSpawning": boolean;
    "DeathFlags": number;
    "HasDeathInfo": boolean;
    "DeathInfoTime": number;
    "DeathInfoOrigin": Vector;
    "PlayerPatchEconIndices": Object;
    "GunGameImmunityColor": Color;
    "GrenadeParameterStashTime": number;
    "GrenadeParametersStashed": boolean;
    "StashedShootAngles": QAngle;
    "StashedGrenadeThrowPosition": Vector;
    "StashedVelocity": Vector;
    "ShootAngleHistory": Object;
    "ThrowPositionHistory": Object;
    "VelocityHistory": Object;
    readonly "PredictedDamageTags": Object;
    "HighestAppliedDamageTagTick": number;
    readonly "Parent": CCSPlayerPawnBase;
    ToPtr: () => string;
    IsValid: () => boolean;
}

declare function CCSPlayerPawn(ptr_or_class: string|AnySDKClass): CCSPlayerPawn;