interface CCSPlayerController {
    readonly "InGameMoneyServices": CCSPlayerController_InGameMoneyServices;
    readonly "InventoryServices": CCSPlayerController_InventoryServices;
    readonly "ActionTrackingServices": CCSPlayerController_ActionTrackingServices;
    readonly "DamageServices": CCSPlayerController_DamageServices;
    "Ping": number;
    "HasCommunicationAbuseMute": boolean;
    "CrosshairCodes": string;
    "PendingTeamNum": number;
    "ForceTeamTime": number;
    "CompTeammateColor": number;
    "EverPlayedOnTeam": boolean;
    "AttemptedToGetColor": boolean;
    "TeammatePreferredColor": number;
    "TeamChanged": boolean;
    "InSwitchTeam": boolean;
    "HasSeenJoinGame": boolean;
    "JustBecameSpectator": boolean;
    "SwitchTeamsOnNextRoundReset": boolean;
    "RemoveAllItemsOnNextRoundReset": boolean;
    "LastJoinTeamTime": number;
    "Clan": string;
    "ClanName": string;
    "CoachingTeam": number;
    "PlayerDominated": number;
    "PlayerDominatingMe": number;
    "CompetitiveRanking": number;
    "CompetitiveWins": number;
    "CompetitiveRankType": number;
    "CompetitiveRankingPredicted_Win": number;
    "CompetitiveRankingPredicted_Loss": number;
    "CompetitiveRankingPredicted_Tie": number;
    "EndMatchNextMapVote": number;
    "ActiveQuestId": number;
    "PlayerTvControlFlags": number;
    "DraftIndex": number;
    "MsQueuedModeDisconnectionTimestamp": number;
    "UiAbandonRecordedReason": number;
    "CannotBeKicked": boolean;
    "EverFullyConnected": boolean;
    "AbandonAllowsSurrender": boolean;
    "AbandonOffersInstantSurrender": boolean;
    "Disconnection1MinWarningPrinted": boolean;
    "ScoreReported": boolean;
    "DisconnectionTick": number;
    "ControllingBot": boolean;
    "HasControlledBotThisRound": boolean;
    "HasBeenControlledByPlayerThisRound": boolean;
    "BotsControlledThisRound": number;
    "CanControlObservedBot": boolean;
    readonly "PlayerPawn": CCSPlayerPawn;
    readonly "ObserverPawn": CCSObserverPawn;
    "DesiredObserverMode": number;
    readonly "DesiredObserverTarget": CEntityInstance;
    "PawnIsAlive": boolean;
    "PawnHealth": number;
    "PawnArmor": number;
    "PawnHasDefuser": boolean;
    "PawnHasHelmet": boolean;
    "PawnCharacterDefIndex": number;
    "PawnLifetimeStart": number;
    "PawnLifetimeEnd": number;
    "PawnBotDifficulty": number;
    readonly "OriginalControllerOfCurrentPawn": CCSPlayerController;
    "Score": number;
    "RoundScore": number;
    "RoundsWon": number;
    "RecentKillQueue": Object;
    "FirstKill": number;
    "KillCount": number;
    "MvpNoMusic": boolean;
    "MvpReason": number;
    "MusicKitID": number;
    "MusicKitMVPs": number;
    "MVPs": number;
    "UpdateCounter": number;
    "SmoothedPing": number;
    readonly "LastHeldVoteTimer": IntervalTimer;
    "ShowHints": boolean;
    "NextTimeCheck": number;
    "JustDidTeamKill": boolean;
    "PunishForTeamKill": boolean;
    "GaveTeamDamageWarning": boolean;
    "GaveTeamDamageWarningThisRound": boolean;
    "DblLastReceivedPacketPlatFloatTime": number;
    "LastTeamDamageWarningTime": number;
    "LastTimePlayerWasDisconnectedForPawnsRemove": number;
    "SuspiciousHitCount": number;
    "NonSuspiciousHitStreak": number;
    "FireBulletsSeedSynchronized": boolean;
    readonly "Parent": CBasePlayerController;
    ToPtr: () => string;
    IsValid: () => boolean;
}

declare function CCSPlayerController(ptr_or_class: string|AnySDKClass): CCSPlayerController;