interface CCSWeaponBase {
    "Removeable": boolean;
    "FireSequenceStartTime": number;
    "FireSequenceStartTimeChange": number;
    "FireSequenceStartTimeAck": number;
    "PlayerFireEvent": number;
    "PlayerFireEventAttackType": number;
    "SeqIdle": number;
    "SeqFirePrimary": number;
    "SeqFireSecondary": number;
    readonly "ThirdPersonFireSequences": Object;
    "CurrentThirdPersonSequence": number;
    "SilencerBoneIndex": number;
    "ThirdPersonSequences": Object;
    "PlayerAmmoStockOnPickup": boolean;
    "RequireUseToTouch": boolean;
    "State": number;
    "LastTimeInAir": number;
    "LastDeployTime": number;
    "LastEmptySoundCmdNum": number;
    "ViewModelIndex": number;
    "ReloadsWithClips": boolean;
    "TimeWeaponIdle": number;
    "FireOnEmpty": boolean;
    readonly "OnPlayerPickup": CEntityIOOutput;
    "WeaponMode": number;
    "TurningInaccuracyDelta": number;
    "TurningInaccuracyEyeDirLast": Vector;
    "TurningInaccuracy": number;
    "AccuracyPenalty": number;
    "LastAccuracyUpdateTime": number;
    "AccuracySmoothedForZoom": number;
    "ScopeZoomEndTime": number;
    "RecoilIndex": number;
    "RecoilIndex1": number;
    "BurstMode": boolean;
    "PostponeFireReadyTicks": number;
    "PostponeFireReadyFrac": number;
    "InReload": boolean;
    "ReloadVisuallyComplete": boolean;
    "DroppedAtTime": number;
    "IsHauledBack": boolean;
    "SilencerOn": boolean;
    "TimeSilencerSwitchComplete": number;
    "OriginalTeamNumber": number;
    "MostRecentTeamNumber": number;
    "DroppedNearBuyZone": boolean;
    "NextAttackRenderTimeOffset": number;
    "CanBePickedUp": boolean;
    "UseCanOverrideNextOwnerTouchTime": boolean;
    "NextOwnerTouchTime": number;
    "NextPrevOwnerTouchTime": number;
    "NextPrevOwnerUseTime": number;
    readonly "PrevOwner": CCSPlayerPawn;
    "DropTick": number;
    "Donated": boolean;
    "LastShotTime": number;
    "WasOwnedByCT": boolean;
    "WasOwnedByTerrorist": boolean;
    "FiredOutOfAmmoEvent": boolean;
    "NumRemoveUnownedWeaponThink": number;
    readonly "IronSightController": CIronSightController;
    "IronSightMode": number;
    "LastLOSTraceFailureTime": number;
    "NumEmptyAttacks": number;
    "WatTickOffset": number;
    readonly "Parent": CBasePlayerWeapon;
    ToPtr: () => string;
    IsValid: () => boolean;
}

declare function CCSWeaponBase(ptr_or_class: string|AnySDKClass): CCSWeaponBase;