interface CCSWeaponBaseVData {
    "WeaponType": number;
    "WeaponCategory": number;
    "GearSlot": number;
    "GearSlotPosition": number;
    "DefaultLoadoutSlot": number;
    "WrongTeamMsg": string;
    "Price": number;
    "KillAward": number;
    "PrimaryReserveAmmoMax": number;
    "SecondaryReserveAmmoMax": number;
    "MeleeWeapon": boolean;
    "HasBurstMode": boolean;
    "IsRevolver": boolean;
    "CannotShootUnderwater": boolean;
    "AnimExtension": string;
    "SilencerType": number;
    "CrosshairMinDistance": number;
    "CrosshairDeltaDistance": number;
    "IsFullAuto": boolean;
    "NumBullets": number;
    readonly "CycleTime": CFiringModeFloat;
    readonly "MaxSpeed": CFiringModeFloat;
    readonly "Spread": CFiringModeFloat;
    readonly "InaccuracyCrouch": CFiringModeFloat;
    readonly "InaccuracyStand": CFiringModeFloat;
    readonly "InaccuracyJump": CFiringModeFloat;
    readonly "InaccuracyLand": CFiringModeFloat;
    readonly "InaccuracyLadder": CFiringModeFloat;
    readonly "InaccuracyFire": CFiringModeFloat;
    readonly "InaccuracyMove": CFiringModeFloat;
    readonly "RecoilAngle": CFiringModeFloat;
    readonly "RecoilAngleVariance": CFiringModeFloat;
    readonly "RecoilMagnitude": CFiringModeFloat;
    readonly "RecoilMagnitudeVariance": CFiringModeFloat;
    readonly "TracerFrequency": CFiringModeInt;
    "InaccuracyJumpInitial": number;
    "InaccuracyJumpApex": number;
    "InaccuracyReload": number;
    "RecoilSeed": number;
    "SpreadSeed": number;
    "TimeToIdleAfterFire": number;
    "IdleInterval": number;
    "AttackMovespeedFactor": number;
    "HeatPerShot": number;
    "InaccuracyPitchShift": number;
    "InaccuracyAltSoundThreshold": number;
    "BotAudibleRange": number;
    "UseRadioSubtitle": string;
    "UnzoomsAfterShot": boolean;
    "HideViewModelWhenZoomed": boolean;
    "ZoomLevels": number;
    "ZoomFOV1": number;
    "ZoomFOV2": number;
    "ZoomTime0": number;
    "ZoomTime1": number;
    "ZoomTime2": number;
    "IronSightPullUpSpeed": number;
    "IronSightPutDownSpeed": number;
    "IronSightFOV": number;
    "IronSightPivotForward": number;
    "IronSightLooseness": number;
    "PivotAngle": QAngle;
    "IronSightEyePos": Vector;
    "Damage": number;
    "HeadshotMultiplier": number;
    "ArmorRatio": number;
    "Penetration": number;
    "Range": number;
    "RangeModifier": number;
    "FlinchVelocityModifierLarge": number;
    "FlinchVelocityModifierSmall": number;
    "RecoveryTimeCrouch": number;
    "RecoveryTimeStand": number;
    "RecoveryTimeCrouchFinal": number;
    "RecoveryTimeStandFinal": number;
    "RecoveryTransitionStartBullet": number;
    "RecoveryTransitionEndBullet": number;
    "ThrowVelocity": number;
    "SmokeColor": Vector;
    readonly "Parent": CBasePlayerWeaponVData;
    ToPtr: () => string;
    IsValid: () => boolean;
}

declare function CCSWeaponBaseVData(ptr_or_class: string|AnySDKClass): CCSWeaponBaseVData;