interface CFeJiggleBone {
    "Flags": number;
    "Length": number;
    "TipMass": number;
    "YawStiffness": number;
    "YawDamping": number;
    "PitchStiffness": number;
    "PitchDamping": number;
    "AlongStiffness": number;
    "AlongDamping": number;
    "AngleLimit": number;
    "MinYaw": number;
    "MaxYaw": number;
    "YawFriction": number;
    "YawBounce": number;
    "MinPitch": number;
    "MaxPitch": number;
    "PitchFriction": number;
    "PitchBounce": number;
    "BaseMass": number;
    "BaseStiffness": number;
    "BaseDamping": number;
    "BaseMinLeft": number;
    "BaseMaxLeft": number;
    "BaseLeftFriction": number;
    "BaseMinUp": number;
    "BaseMaxUp": number;
    "BaseUpFriction": number;
    "BaseMinForward": number;
    "BaseMaxForward": number;
    "BaseForwardFriction": number;
    "Radius0": number;
    "Radius1": number;
    "Point0": Vector;
    "Point1": Vector;
    "CollisionMask": number;
    ToPtr: () => string;
    IsValid: () => boolean;
}

declare function CFeJiggleBone(ptr_or_class: string|AnySDKClass): CFeJiggleBone;