interface CGenericConstraint {
    "LinearMotionX": number;
    "LinearMotionY": number;
    "LinearMotionZ": number;
    "LinearFrequencyX": number;
    "LinearFrequencyY": number;
    "LinearFrequencyZ": number;
    "LinearDampingRatioX": number;
    "LinearDampingRatioY": number;
    "LinearDampingRatioZ": number;
    "MaxLinearImpulseX": number;
    "MaxLinearImpulseY": number;
    "MaxLinearImpulseZ": number;
    "BreakAfterTimeX": number;
    "BreakAfterTimeY": number;
    "BreakAfterTimeZ": number;
    "BreakAfterTimeStartTimeX": number;
    "BreakAfterTimeStartTimeY": number;
    "BreakAfterTimeStartTimeZ": number;
    "BreakAfterTimeThresholdX": number;
    "BreakAfterTimeThresholdY": number;
    "BreakAfterTimeThresholdZ": number;
    "NotifyForceX": number;
    "NotifyForceY": number;
    "NotifyForceZ": number;
    "NotifyForceMinTimeX": number;
    "NotifyForceMinTimeY": number;
    "NotifyForceMinTimeZ": number;
    "NotifyForceLastTimeX": number;
    "NotifyForceLastTimeY": number;
    "NotifyForceLastTimeZ": number;
    "AxisNotifiedX": boolean;
    "AxisNotifiedY": boolean;
    "AxisNotifiedZ": boolean;
    "AngularMotionX": number;
    "AngularMotionY": number;
    "AngularMotionZ": number;
    "AngularFrequencyX": number;
    "AngularFrequencyY": number;
    "AngularFrequencyZ": number;
    "AngularDampingRatioX": number;
    "AngularDampingRatioY": number;
    "AngularDampingRatioZ": number;
    "MaxAngularImpulseX": number;
    "MaxAngularImpulseY": number;
    "MaxAngularImpulseZ": number;
    readonly "NotifyForceReachedX": CEntityIOOutput;
    readonly "NotifyForceReachedY": CEntityIOOutput;
    readonly "NotifyForceReachedZ": CEntityIOOutput;
    readonly "Parent": CPhysConstraint;
    ToPtr: () => string;
    IsValid: () => boolean;
}

declare function CGenericConstraint(ptr_or_class: string|AnySDKClass): CGenericConstraint;