interface CLightComponent {
    readonly "__pChainEntity": CNetworkVarChainer;
    "Color": Color;
    "SecondaryColor": Color;
    "Brightness": number;
    "BrightnessScale": number;
    "BrightnessMult": number;
    "Range": number;
    "Falloff": number;
    "Attenuation0": number;
    "Attenuation1": number;
    "Attenuation2": number;
    "Theta": number;
    "Phi": number;
    "Cascades": number;
    "CastShadows": number;
    "ShadowWidth": number;
    "ShadowHeight": number;
    "RenderDiffuse": boolean;
    "RenderSpecular": number;
    "RenderTransmissive": boolean;
    "OrthoLightWidth": number;
    "OrthoLightHeight": number;
    "Style": number;
    "Pattern": string;
    "CascadeRenderStaticObjects": number;
    "ShadowCascadeCrossFade": number;
    "ShadowCascadeDistanceFade": number;
    "ShadowCascadeDistance0": number;
    "ShadowCascadeDistance1": number;
    "ShadowCascadeDistance2": number;
    "ShadowCascadeDistance3": number;
    "ShadowCascadeResolution0": number;
    "ShadowCascadeResolution1": number;
    "ShadowCascadeResolution2": number;
    "ShadowCascadeResolution3": number;
    "UsesBakedShadowing": boolean;
    "ShadowPriority": number;
    "BakedShadowIndex": number;
    "RenderToCubemaps": boolean;
    "DirectLight": number;
    "IndirectLight": number;
    "FadeMinDist": number;
    "FadeMaxDist": number;
    "ShadowFadeMinDist": number;
    "ShadowFadeMaxDist": number;
    "Enabled": boolean;
    "Flicker": boolean;
    "PrecomputedFieldsValid": boolean;
    "PrecomputedBoundsMins": Vector;
    "PrecomputedBoundsMaxs": Vector;
    "PrecomputedOBBOrigin": Vector;
    "PrecomputedOBBAngles": QAngle;
    "PrecomputedOBBExtent": Vector;
    "PrecomputedMaxRange": number;
    "FogLightingMode": number;
    "FogContributionStength": number;
    "NearClipPlane": number;
    "SkyColor": Color;
    "SkyIntensity": number;
    "SkyAmbientBounce": Color;
    "UseSecondaryColor": boolean;
    "MixedShadows": boolean;
    "LightStyleStartTime": number;
    "CapsuleLength": number;
    "MinRoughness": number;
    "PvsModifyEntity": boolean;
    readonly "Parent": CEntityComponent;
    ToPtr: () => string;
    IsValid: () => boolean;
}

declare function CLightComponent(ptr_or_class: string|AnySDKClass): CLightComponent;