interface CLogicNPCCounter {
    readonly "OnMinCountAll": CEntityIOOutput;
    readonly "OnMaxCountAll": CEntityIOOutput;
    readonly "OnMinCount_1": CEntityIOOutput;
    readonly "OnMaxCount_1": CEntityIOOutput;
    readonly "OnMinCount_2": CEntityIOOutput;
    readonly "OnMaxCount_2": CEntityIOOutput;
    readonly "OnMinCount_3": CEntityIOOutput;
    readonly "OnMaxCount_3": CEntityIOOutput;
    readonly "Source": CEntityInstance;
    "SourceEntityName": string;
    "DistanceMax": number;
    "Disabled": boolean;
    "MinCountAll": number;
    "MaxCountAll": number;
    "MinFactorAll": number;
    "MaxFactorAll": number;
    "NPCClassname_1": string;
    "NPCState_1": number;
    "InvertState_1": boolean;
    "MinCount_1": number;
    "MaxCount_1": number;
    "MinFactor_1": number;
    "MaxFactor_1": number;
    "DefaultDist_1": number;
    "NPCClassname_2": string;
    "NPCState_2": number;
    "InvertState_2": boolean;
    "MinCount_2": number;
    "MaxCount_2": number;
    "MinFactor_2": number;
    "MaxFactor_2": number;
    "DefaultDist_2": number;
    "NPCClassname_3": string;
    "NPCState_3": number;
    "InvertState_3": boolean;
    "MinCount_3": number;
    "MaxCount_3": number;
    "MinFactor_3": number;
    "MaxFactor_3": number;
    "DefaultDist_3": number;
    readonly "Parent": CBaseEntity;
    ToPtr: () => string;
    IsValid: () => boolean;
}

declare function CLogicNPCCounter(ptr_or_class: string|AnySDKClass): CLogicNPCCounter;