interface CMapInfo {
    "BuyingStatus": number;
    "BombRadius": number;
    "PetPopulation": number;
    "UseNormalSpawnsForDM": boolean;
    "DisableAutoGeneratedDMSpawns": boolean;
    "BotMaxVisionDistance": number;
    "HostageCount": number;
    "FadePlayerVisibilityFarZ": boolean;
    "RainTraceToSkyEnabled": boolean;
    readonly "Parent": CPointEntity;
    ToPtr: () => string;
    IsValid: () => boolean;
}

declare function CMapInfo(ptr_or_class: string|AnySDKClass): CMapInfo;