interface CParticleSystemDefinition {
    "BehaviorVersion": number;
    readonly "PreEmissionOperators": Object;
    readonly "Emitters": Object;
    readonly "Initializers": Object;
    readonly "Operators": Object;
    readonly "ForceGenerators": Object;
    readonly "Constraints": Object;
    readonly "Renderers": Object;
    readonly "Children": Object;
    "FirstMultipleOverride_BackwardCompat": number;
    "InitialParticles": number;
    "MaxParticles": number;
    "GroupID": number;
    "BoundingBoxMin": Vector;
    "BoundingBoxMax": Vector;
    "DepthSortBias": number;
    "SortOverridePositionCP": number;
    "InfiniteBounds": boolean;
    "EnableNamedValues": boolean;
    "NamedValueDomain": string;
    readonly "NamedValueLocals": Object;
    "ConstantColor": Color;
    "ConstantNormal": Vector;
    "ConstantRadius": number;
    "ConstantRotation": number;
    "ConstantRotationSpeed": number;
    "ConstantLifespan": number;
    "ConstantSequenceNumber": number;
    "ConstantSequenceNumber1": number;
    "SnapshotControlPoint": number;
    "CullRadius": number;
    "CullFillCost": number;
    "CullControlPoint": number;
    "FallbackMaxCount": number;
    "PreSimulationTime": number;
    "StopSimulationAfterTime": number;
    "MaximumTimeStep": number;
    "MaximumSimTime": number;
    "MinimumSimTime": number;
    "MinimumTimeStep": number;
    "MinimumFrames": number;
    "MinCPULevel": number;
    "MinGPULevel": number;
    "NoDrawTimeToGoToSleep": number;
    "MaxDrawDistance": number;
    "StartFadeDistance": number;
    "MaxCreationDistance": number;
    "AggregationMinAvailableParticles": number;
    "AggregateRadius": number;
    "ShouldBatch": boolean;
    "ShouldHitboxesFallbackToRenderBounds": boolean;
    "ShouldHitboxesFallbackToSnapshot": boolean;
    "ShouldHitboxesFallbackToCollisionHulls": boolean;
    "ViewModelEffect": number;
    "ScreenSpaceEffect": boolean;
    "TargetLayerID": string;
    "SkipRenderControlPoint": number;
    "AllowRenderControlPoint": number;
    "ShouldSort": boolean;
    readonly "ControlPointConfigurations": Object;
    ToPtr: () => string;
    IsValid: () => boolean;
}

declare function CParticleSystemDefinition(ptr_or_class: string|AnySDKClass): CParticleSystemDefinition;