interface CParticleFloatInput {
    "Type": number;
    "MapType": number;
    "LiteralValue": number;
    "ControlPoint": number;
    readonly "ScalarAttribute": ParticleAttributeIndex_t;
    readonly "VectorAttribute": ParticleAttributeIndex_t;
    "VectorComponent": number;
    "RandomMin": number;
    "RandomMax": number;
    "HasRandomSignFlip": boolean;
    "RandomSeed": number;
    "RandomMode": number;
    "LOD0": number;
    "LOD1": number;
    "LOD2": number;
    "LOD3": number;
    readonly "NoiseInputVectorAttribute": ParticleAttributeIndex_t;
    "NoiseOutputMin": number;
    "NoiseOutputMax": number;
    "NoiseScale": number;
    "NoiseOffsetRate": Vector;
    "NoiseOffset": number;
    "NoiseOctaves": number;
    "NoiseTurbulence": number;
    "NoiseType": number;
    "NoiseModifier": number;
    "NoiseTurbulenceScale": number;
    "NoiseTurbulenceMix": number;
    "NoiseImgPreviewScale": number;
    "NoiseImgPreviewLive": boolean;
    "NoCameraFallback": number;
    "UseBoundsCenter": boolean;
    "InputMode": number;
    "MultFactor": number;
    "Input0": number;
    "Input1": number;
    "Output0": number;
    "Output1": number;
    "NotchedRangeMin": number;
    "NotchedRangeMax": number;
    "NotchedOutputOutside": number;
    "NotchedOutputInside": number;
    "RoundType": number;
    "BiasType": number;
    "BiasParameter": number;
    readonly "Parent": CParticleInput;
    ToPtr: () => string;
    IsValid: () => boolean;
}

declare function CParticleFloatInput(ptr_or_class: string|AnySDKClass): CParticleFloatInput;