interface CScriptedSequence {
    "Entry": string;
    "PreIdle": string;
    "Play": string;
    "PostIdle": string;
    "ModifierToAddOnPlay": string;
    "NextScript": string;
    "Entity": string;
    "SyncGroup": string;
    "MoveTo": number;
    "MoveToGait": number;
    "HeldWeaponBehavior": number;
    "IsPlayingPreIdle": boolean;
    "IsPlayingEntry": boolean;
    "IsPlayingAction": boolean;
    "IsPlayingPostIdle": boolean;
    "DontRotateOther": boolean;
    "IsRepeatable": boolean;
    "ShouldLeaveCorpse": boolean;
    "StartOnSpawn": boolean;
    "DisallowInterrupts": boolean;
    "CanOverrideNPCState": boolean;
    "DontTeleportAtEnd": boolean;
    "HighPriority": boolean;
    "HideDebugComplaints": boolean;
    "ContinueOnDeath": boolean;
    "LoopPreIdleSequence": boolean;
    "LoopActionSequence": boolean;
    "LoopPostIdleSequence": boolean;
    "SynchPostIdles": boolean;
    "IgnoreLookAt": boolean;
    "IgnoreGravity": boolean;
    "DisableNPCCollisions": boolean;
    "KeepAnimgraphLockedPost": boolean;
    "DontAddModifiers": boolean;
    "Radius": number;
    "Repeat": number;
    "PlayAnimFadeInTime": number;
    "MoveInterpTime": number;
    "AngRate": number;
    "WaitUntilMoveCompletesToStartAnimation": boolean;
    "NotReadySequenceCount": number;
    "StartTime": number;
    "WaitForBeginSequence": boolean;
    "Saved_effects": number;
    "SavedFlags": number;
    "SavedCollisionGroup": number;
    "Interruptable": boolean;
    "SequenceStarted": boolean;
    "PositionRelativeToOtherEntity": boolean;
    readonly "TargetEnt": CBaseEntity;
    readonly "NextCine": CScriptedSequence;
    "Thinking": boolean;
    "InitiatedSelfDelete": boolean;
    "IsTeleportingDueToMoveTo": boolean;
    "AllowCustomInterruptConditions": boolean;
    readonly "ForcedTarget": CBaseAnimGraph;
    "DontCancelOtherSequences": boolean;
    "ForceSynch": boolean;
    "PreventUpdateYawOnFinish": boolean;
    "EnsureOnNavmeshOnFinish": boolean;
    "OnDeathBehavior": number;
    "ConflictResponse": number;
    readonly "OnBeginSequence": CEntityIOOutput;
    readonly "OnActionStartOrLoop": CEntityIOOutput;
    readonly "OnEndSequence": CEntityIOOutput;
    readonly "OnPostIdleEndSequence": CEntityIOOutput;
    readonly "OnCancelSequence": CEntityIOOutput;
    readonly "OnCancelFailedSequence": CEntityIOOutput;
    readonly "OnScriptEvent": Object;
    readonly "InteractionMainEntity": CBaseEntity;
    "PlayerDeathBehavior": number;
    readonly "Parent": CBaseEntity;
    ToPtr: () => string;
    IsValid: () => boolean;
}

declare function CScriptedSequence(ptr_or_class: string|AnySDKClass): CScriptedSequence;