interface RnBodyDesc_t {
    "DebugName": string;
    "Position": Vector;
    "LinearVelocity": Vector;
    "AngularVelocity": Vector;
    "LocalMassCenter": Vector;
    "LocalInertiaInv": Object;
    "MassInv": number;
    "GameMass": number;
    "InertiaScaleInv": number;
    "LinearDamping": number;
    "AngularDamping": number;
    "LinearDrag": number;
    "AngularDrag": number;
    "LinearBuoyancyDrag": number;
    "AngularBuoyancyDrag": number;
    "LastAwakeForceAccum": Vector;
    "LastAwakeTorqueAccum": Vector;
    "BuoyancyFactor": number;
    "GravityScale": number;
    "TimeScale": number;
    "BodyType": number;
    "GameIndex": number;
    "GameFlags": number;
    "MinVelocityIterations": number;
    "MinPositionIterations": number;
    "MassPriority": number;
    "Enabled": boolean;
    "Sleeping": boolean;
    "IsContinuousEnabled": boolean;
    "DragEnabled": boolean;
    "BuoyancyDragEnabled": boolean;
    "GravityDisabled": boolean;
    "SpeculativeEnabled": boolean;
    "HasShadowController": boolean;
    ToPtr: () => string;
    IsValid: () => boolean;
}

declare function RnBodyDesc_t(ptr_or_class: string|AnySDKClass): RnBodyDesc_t;