name: "Types Compiler"

on:
    push:
        branches:
            - '**'

    pull_request:


jobs:
    build:
        permissions:
            contents: write
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repository
              uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - name: Setup Node version
              uses: actions/setup-node@v4
              with:
                node-version: '20.17.0'

            - name: Generate Types
              run: bash generate.sh
            
            - name: Setup Git
              run: |
                git config user.name "${{ github.actor }}"
                git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"